language: node_js

node_js:
  - 0.10.26
  
install:
  - npm install contextify
  
script:
  - npm test
after_script: 
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u tdd 
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
